version: '3'

services:

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://mypostgresql.cvkwiymisn6z.us-east-1.rds.amazonaws.com:5432/postregs
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: freshhukfresh
    restart: no


